import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { save, open } from "@tauri-apps/plugin-dialog";
import { Download, Upload, ClipboardCopy, ClipboardPaste } from "lucide-react";
import Page from "@/components/views/Page";
import { useConfigStore } from "@/stores/config";
import { useToastStore } from "@/stores/toasts";
import { parseConfig } from "@/utils/parse";

const EXPORT_HEADER = "# Generated by Ghostgen\n\n";

export default function ImportExportPage() {
  const diff = useConfigStore((s) => s.diff);
  const stringify = useConfigStore((s) => s.stringify);
  const load = useConfigStore((s) => s.load);
  const addToast = useToastStore((s) => s.add);

  const [preview, setPreview] = useState<Record<string, unknown> | null>(null);

  const changedKeys = Object.keys(diff());
  const changeCount = changedKeys.length;
  const hasChanges = changeCount > 0;

  const handleExportToFile = async () => {
    try {
      const path = await save({
        defaultPath: "ghostty-config",
        filters: [{ name: "All Files", extensions: ["*"] }],
      });
      if (!path) return;
      const content = EXPORT_HEADER + stringify();
      await invoke("write_file", { path, content });
      addToast(`Exported ${changeCount} settings to file`, "success");
    } catch (err) {
      addToast(`Export failed: ${err}`, "error");
    }
  };

  const handleExportToClipboard = async () => {
    try {
      const content = EXPORT_HEADER + stringify();
      await navigator.clipboard.writeText(content);
      addToast(`Copied ${changeCount} settings to clipboard`, "success");
    } catch (err) {
      addToast(`Failed to copy to clipboard: ${err}`, "error");
    }
  };

  const handleImportFromFile = async () => {
    try {
      const path = await open({
        multiple: false,
        filters: [{ name: "Config Files", extensions: ["*"] }],
      });
      if (!path) return;
      const text = await invoke<string>("read_file", { path });
      const parsed = parseConfig(text);
      const keys = Object.keys(parsed);
      if (keys.length === 0) {
        addToast("No valid settings found in file", "error");
        return;
      }
      setPreview(parsed);
    } catch (err) {
      addToast(`Import failed: ${err}`, "error");
    }
  };

  const handleImportFromClipboard = async () => {
    try {
      const text = await navigator.clipboard.readText();
      if (!text.trim()) {
        addToast("Clipboard is empty", "error");
        return;
      }
      const parsed = parseConfig(text);
      const keys = Object.keys(parsed);
      if (keys.length === 0) {
        addToast("No valid settings found in clipboard", "error");
        return;
      }
      setPreview(parsed);
    } catch (err) {
      addToast(`Failed to read clipboard: ${err}`, "error");
    }
  };

  const handleConfirmImport = () => {
    if (!preview) return;
    const count = Object.keys(preview).length;
    load(preview);
    setPreview(null);
    addToast(`Imported ${count} settings`, "success");
  };

  return (
    <Page title="Import / Export">
      <div className="ie-grid">
        <button
          className="ie-card"
          disabled={!hasChanges}
          onClick={handleExportToFile}
        >
          <span className="ie-card-icon"><Download size={24} /></span>
          <span className="ie-card-title">Export to File</span>
          <span className="ie-card-desc">
            {hasChanges
              ? `Save ${changeCount} changed setting${changeCount !== 1 ? "s" : ""} to a file`
              : "No changes to export"}
          </span>
        </button>

        <button
          className="ie-card"
          disabled={!hasChanges}
          onClick={handleExportToClipboard}
        >
          <span className="ie-card-icon"><ClipboardCopy size={24} /></span>
          <span className="ie-card-title">Export to Clipboard</span>
          <span className="ie-card-desc">
            {hasChanges
              ? `Copy ${changeCount} changed setting${changeCount !== 1 ? "s" : ""} to clipboard`
              : "No changes to export"}
          </span>
        </button>

        <button className="ie-card" onClick={handleImportFromFile}>
          <span className="ie-card-icon"><Upload size={24} /></span>
          <span className="ie-card-title">Import from File</span>
          <span className="ie-card-desc">Load settings from a Ghostty config file</span>
        </button>

        <button className="ie-card" onClick={handleImportFromClipboard}>
          <span className="ie-card-icon"><ClipboardPaste size={24} /></span>
          <span className="ie-card-title">Import from Clipboard</span>
          <span className="ie-card-desc">Paste settings from your clipboard</span>
        </button>
      </div>

      {preview && (
        <div className="dialog-overlay" onClick={() => setPreview(null)}>
          <div className="dialog-box" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 500 }}>
            <h3 className="dialog-title">Import Preview</h3>
            <p className="dialog-message">
              The following {Object.keys(preview).length} setting{Object.keys(preview).length !== 1 ? "s" : ""} will be applied:
            </p>
            <div className="import-preview-list">
              {Object.entries(preview).map(([key, value]) => (
                <div key={key} className="import-preview-row">
                  <span className="import-preview-key">{key}</span>
                  <span className="import-preview-value">
                    {Array.isArray(value) ? `[${value.length} items]` : String(value)}
                  </span>
                </div>
              ))}
            </div>
            <div className="dialog-actions">
              <button className="dialog-btn dialog-btn-cancel" onClick={() => setPreview(null)}>
                Cancel
              </button>
              <button className="dialog-btn dialog-btn-confirm" onClick={handleConfirmImport}>
                Apply {Object.keys(preview).length} Settings
              </button>
            </div>
          </div>
        </div>
      )}
    </Page>
  );
}
